In [3]:
# Importação das Bibliotecas
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.datasets import load_boston
 

In [4]:
# Carregando o Dataset
boston = load_boston()
dataset = pd.DataFrame(boston.data, columns = boston.feature_names)
dataset['target'] = boston.target

In [5]:
dataset

CRIM    ZN  INDUS  CHAS    NOX  ...    TAX  PTRATIO       B  LSTAT  target
0    0.00632  18.0   2.31   0.0  0.538  ...  296.0     15.3  396.90   4.98    24.0
1    0.02731   0.0   7.07   0.0  0.469  ...  242.0     17.8  396.90   9.14    21.6
2    0.02729   0.0   7.07   0.0  0.469  ...  242.0     17.8  392.83   4.03    34.7
3    0.03237   0.0   2.18   0.0  0.458  ...  222.0     18.7  394.63   2.94    33.4
4    0.06905   0.0   2.18   0.0  0.458  ...  222.0     18.7  396.90   5.33    36.2
..       ...   ...    ...   ...    ...  ...    ...      ...     ...    ...     ...
501  0.06263   0.0  11.93   0.0  0.573  ...  273.0     21.0  391.99   9.67    22.4
502  0.04527   0.0  11.93   0.0  0.573  ...  273.0     21.0  396.90   9.08    20.6
503  0.06076   0.0  11.93   0.0  0.573  ...  273.0     21.0  396.90   5.64    23.9
504  0.10959   0.0  11.93   0.0  0.573  ...  273.0     21.0  393.45   6.48    22.0
505  0.04741   0.0  11.93   0.0  0.573  ...  273.0     21.0  396.90   7.88    11.9

[506 rows x 14 columns]

In [22]:
# Formato do Dataset 
print("Boston housing dataset tem {} observações com {} variáveis cada uma.".format(*dataset.shape))

Boston housing dataset tem 506 observações com 14 variáveis cada uma.


In [11]:
dataset.shape

(506, 14)

In [23]:
dataset.head()


CRIM    ZN  INDUS  CHAS    NOX  ...    TAX  PTRATIO       B  LSTAT  target
0  0.00632  18.0   2.31   0.0  0.538  ...  296.0     15.3  396.90   4.98    24.0
1  0.02731   0.0   7.07   0.0  0.469  ...  242.0     17.8  396.90   9.14    21.6
2  0.02729   0.0   7.07   0.0  0.469  ...  242.0     17.8  392.83   4.03    34.7
3  0.03237   0.0   2.18   0.0  0.458  ...  222.0     18.7  394.63   2.94    33.4
4  0.06905   0.0   2.18   0.0  0.458  ...  222.0     18.7  396.90   5.33    36.2

[5 rows x 14 columns]

In [24]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    float64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    float64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  target   506 non-null    float64
dtypes: float64(14)
memory usage: 55.5 KB


In [28]:
dataset.dtypes

CRIM       float64
ZN         float64
INDUS      float64
CHAS       float64
NOX        float64
RM         float64
AGE        float64
DIS        float64
RAD        float64
TAX        float64
PTRATIO    float64
B          float64
LSTAT      float64
target     float64
dtype: object

In [30]:
dataset.describe()

CRIM          ZN       INDUS  ...           B       LSTAT      target
count  506.000000  506.000000  506.000000  ...  506.000000  506.000000  506.000000
mean     3.613524   11.363636   11.136779  ...  356.674032   12.653063   22.532806
std      8.601545   23.322453    6.860353  ...   91.294864    7.141062    9.197104
min      0.006320    0.000000    0.460000  ...    0.320000    1.730000    5.000000
25%      0.082045    0.000000    5.190000  ...  375.377500    6.950000   17.025000
50%      0.256510    0.000000    9.690000  ...  391.440000   11.360000   21.200000
75%      3.677083   12.500000   18.100000  ...  396.225000   16.955000   25.000000
max     88.976200  100.000000   27.740000  ...  396.900000   37.970000   50.000000

[8 rows x 14 columns]

In [31]:
dataset.isna().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
target     0
dtype: int64

In [32]:
dataset.isnull().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
target     0
dtype: int64

In [33]:
dataset.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...  
501    False
502    False
503    False
504    False
505    False
Length: 506, dtype: bool

In [38]:
# Variáveis IMPORTANTES
# Importantes = dataset.feature_importances_
# print(Importantes)

In [45]:
dataset.corr()


CRIM        ZN     INDUS  ...         B     LSTAT    target
CRIM     1.000000 -0.200469  0.406583  ... -0.385064  0.455621 -0.388305
ZN      -0.200469  1.000000 -0.533828  ...  0.175520 -0.412995  0.360445
INDUS    0.406583 -0.533828  1.000000  ... -0.356977  0.603800 -0.483725
CHAS    -0.055892 -0.042697  0.062938  ...  0.048788 -0.053929  0.175260
NOX      0.420972 -0.516604  0.763651  ... -0.380051  0.590879 -0.427321
RM      -0.219247  0.311991 -0.391676  ...  0.128069 -0.613808  0.695360
AGE      0.352734 -0.569537  0.644779  ... -0.273534  0.602339 -0.376955
DIS     -0.379670  0.664408 -0.708027  ...  0.291512 -0.496996  0.249929
RAD      0.625505 -0.311948  0.595129  ... -0.444413  0.488676 -0.381626
TAX      0.582764 -0.314563  0.720760  ... -0.441808  0.543993 -0.468536
PTRATIO  0.289946 -0.391679  0.383248  ... -0.177383  0.374044 -0.507787
B       -0.385064  0.175520 -0.356977  ...  1.000000 -0.366087  0.333461
LSTAT    0.455621 -0.412995  0.603800  ... -0.366087  1.000000 -0.737663
target  -0.388305  0.360445 -0.483725  ...  0.333461 -0.737663  1.000000

[14 rows x 14 columns]

In [39]:
# Coletando X e Y com as 4 variáveis mais importatntes
X = dataset[['LSTAT','RM', 'DIS', 'PTRATIO']]
y = dataset['target'].values

In [42]:
X.head()

LSTAT     RM     DIS  PTRATIO
0   4.98  6.575  4.0900     15.3
1   9.14  6.421  4.9671     17.8
2   4.03  7.185  4.9671     17.8
3   2.94  6.998  6.0622     18.7
4   5.33  7.147  6.0622     18.7

In [43]:
y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [50]:
# Dados de Treino e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 7)


In [51]:
# Cria Módelo
modelo = LinearRegression()
modelo

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [53]:
# Treinar o modelo
modelo_v1 = modelo.fit(X_train, y_train)

In [55]:
# Nova Previsões
previsões = modelo_v1.predict(X_test)
previsões

array([21.77824325, 19.21648457, 19.62074535, 20.46330314, 15.5873    ,
       12.85678689, 21.23214007, 27.64136662, 28.10869023, 17.03915481,
        4.24784845, 32.14300288, 19.18231115, 18.91410186, 35.54478438,
       21.20721276, 27.49006143, 32.21945868,  9.77532087, 23.9570629 ,
       19.28090949, 28.60887795, 37.550173  , 13.16374183, 10.39286023,
       17.07054496, 32.56130813, 27.05680032, 24.73756419, 26.04314104,
       20.5810515 , 31.10804888, 31.59642971, 19.75270493, 39.93559967,
       20.07757203, 18.86058664, 21.39502305, 21.59976255, 27.20987699,
       26.4342392 , 18.01924157, 13.76649001, 26.19475446, 19.18876334,
       15.81772581, 25.49334142, 20.60012438, 25.05340763,  8.63146586,
       28.34712221, 25.37452518, 20.64846448, 39.35242924, 19.65269295,
       21.25734371, 20.16320791, 20.60101956, 23.71665732, 19.68509147,
       20.08986204, 34.94728679, 16.66413054, 20.69334457, 25.06334321,
       40.47766645, 21.16716075, 22.00481241, 22.59663425, 29.34

In [56]:
# Cálcular o r2 do modelo
r2_score(y_test, previsões)

0.5381691929033983

In [66]:
# Novo Cálculo com as novas variáveis(ZN, CHAS, DIS, B e RM)
# Coletando X e Y com as 4 variáveis mais importatntes
X = dataset[['ZN','RM', 'DIS', 'B']]
y = dataset['target'].values

In [67]:
X.head()

ZN     RM     DIS       B
0  18.0  6.575  4.0900  396.90
1   0.0  6.421  4.9671  396.90
2   0.0  7.185  4.9671  392.83
3   0.0  6.998  6.0622  394.63
4   0.0  7.147  6.0622  396.90

In [68]:
y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [69]:
# Dados de Treino e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 7)


In [70]:
# Cria Módelo
modelo = LinearRegression()
modelo

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [71]:
# Treinar o modelo
modelo_v1 = modelo.fit(X_train, y_train)
modelo_v1

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [72]:
# Nova Previsões
previsões = modelo_v1.predict(X_test)
previsões

array([24.08898411, 19.21343541, 20.99292623, 19.87910996, 11.20006058,
       14.86852893, 22.47098604, 24.35946411, 26.33791591, 11.13943158,
       10.06273651, 30.47663186, 22.67073402, 22.57847052, 37.11118482,
       24.4633236 , 27.08938184, 30.50892859, 16.03382864, 20.31111187,
       25.0395495 , 29.52798156, 38.40867673, 17.12621531, 10.9492503 ,
       18.78716654, 34.91701619, 27.76694452, 23.57385646, 26.8713624 ,
       21.8357035 , 30.82598762, 30.26585105, 17.08171184, 34.65111422,
       18.09105153, 18.72967941, 17.90669387, 21.44567083, 29.45962573,
       24.22635182, 25.86801309, 19.35371869, 27.63534759, 21.35147866,
       16.07060703, 22.86512895, 21.51285425, 14.69513091, -4.94266369,
       25.03673543, 23.46116062,  9.11109531, 44.87151951, 15.9990518 ,
       21.73167095, 18.75101165, 22.47555247, 21.97186897, 19.78740185,
       19.99560397, 33.54277907, 18.73921432, 20.03644517, 19.29529728,
       42.85893712, 22.57685189, 23.77134936, 20.70980976, 26.28

In [73]:
# Cálcular o r2 do modelo
r2_score(y_test, previsões)

0.2707501701611812

In [ ]:
# r2 x r2 com outras variáveis
# = 0.5381691929033983
# = 0.27103360038690805
